language: php

php:
  - 5.6.4
  - 5.6
  - 7.0

sudo: false

before_install:
  - pecl install swoole

install: travis_retry composer install --no-interaction --prefer-source

script: vendor/bin/phpunit
